### ISSUE TITLE
Problem mapping SocketCAN to CAN0 with Kvaser Leaf 

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc-joystick-commander#14]
As it is described in documentation:
For example with a Kvaser Leaf Light attached, using a bitrate of 500000 and a CAN channel of 0:
 sudo ip link set can0 type can bitrate 500000
 sudo ip link set up can0

After issuing command : sudo ip link set can0 type can bitrate 500000
Get message: Cannot find device "can0"

Tried to issue commands:
sudo modprobe can
sudo modprobe can_raw
sudo modprobe kvaser_usb

But did not helped.

Can you give directions/cli commands to get CAN0 working for Kvaser Leaf.

**Comment by vertexmachina** [comment]
Do you currently have, or have you ever had, Kvaser's CANlib installed? When those are installed, they blacklist socketcan which will cause problems.

**Comment by rg4444** [comment]
Yes CANlib is currently installed.
Compiled and installed as Kvaser Linux instructed.
Current using Linux 4.8.0-51-generic kernel on Ubuntu 16.04

**Comment by vertexmachina** [comment]
You'll need to uninstall CANlib and then reboot for socketcan to work.

Follow this procedure:

- Download the linuxcan tarball again if you no longer have it: http://www.kvaser.com/go/0004/linux
- Extract linuxcan: tar -xf linuxcan.tar.gz
- Inside of the linuxcan directory, run `make` to build everything which is required before you can uninstall
- Now uninstall CANlib with `sudo make uninstall`

You should see something like the following:

```
Uninstalling pciefd
Remove SocketCAN Kvaser PCI driver from blacklist.
Uninstalling pcican2
Remove SocketCAN Kvaser PCI driver from blacklist.
Uninstalling pcican
Remove SocketCAN Kvaser PCI driver from blacklist.
Uninstalling virtualcan
Uninstalling usbcanII
Remove SocketCAN Kvaser USB driver from blacklist.
Uninstalling mhydra
Uninstalling leaf
Remove SocketCAN Kvaser USB driver from blacklist.
Uninstalling common
```

Now you can reboot and the `ip link` commands should work.

**Comment by rg4444** [comment]
Did everything to ... and the ip link commands should work. 
sudo ip link set can0 type can bitrate 500000
Cannot find device "can0"
And got same result

**Comment by vertexmachina** [comment]
You'll need to get socketcan working before you can use OSCC. I suggest you make sure you've fully uninstalled Kvaser's CANlib and try again. As a last resort you can reinstall Ubuntu to ensure CANlib is not on the machine.

**Comment by Markster25** [comment]
@rg4444 any luck with this error? I've been having issues trying to run candump because I cannot setup the can0 interface.  I'm getting the same error "Cannot find device 'can0'"

**Comment by sohamm17** [comment]
It worked for me. I had to uninstall Kvaser's linuxcan (canlib) and then replug the can, can_raw and can_dev modules.

**Comment by panc8170** [comment]
was there any updates on this? I am facing same problem, will I need to uninstall it every time?
also after I uninstall, and after one reboot, if I try to run sudo modprobe can it doesnt work - maybe because the drivers are gone now?
