### ISSUE TITLE
After presing Start, programm stops without errors.

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc-joystick-commander#15]
./oscc-joystick-commander 0
Opening CAN channel: can0
Found 1 devices -- connecting to device at system index 0 - GUID: 030000006d0400001dc2000014400000
Waiting for joystick controls to zero
Joystick controls successfully initialized

Control Ready:
    START - Enable controls
    BACK - Disable controls
    LEFT TRIGGER - Brake
    RIGHT TRIGGER - Throttle
    LEFT STICK - Steering
Enable controls
andris@pilotdev01:/srv/oscc-joystick-commander/build$

**Comment by vertexmachina** [comment]
This can happen if you did not properly set up socketcan (you should see `can0` listed if you do `ifconfig`), or if the Kvaser Leaf is not connected to the Control CAN bus of the OSCC modules.
