### ISSUE TITLE
After wiring up all the modules the system does not work

### ISSUE THREAD

**Issue by ramanathanrm95** [PolySync/oscc-joystick-commander#16]
I wired up and flashed all the modules without any errors.
I installed the joystickcommander package and followed the steps with no errors.
When I run the ./joystickcommand, the command window initializes and when I press start button, the values of steering, brake and throttle are displayed and when the left stick is toggled, the steering value updates, but after a second, program closes by giving disable controls message and there is no change in the steering wheel position of the car even when the values are updated.

I built the can-gateway module by stacking 2 CAN shields and connecting one of them to Kvaser converter and then to laptop (Modified CS pin of one of the shields to pin 10 --> Connected to Kvaser converter, did not change the resistor)
Connected the steering module as given in GitHub.
Powered all the modules through the laptop itself.
Connected the joystick to the laptop.

Should there be a control can bus separately or can I just use the laptop as control can bus?

This is my current connection:

STEERING --> CAN GATEWAY --> OBD CAN
LAPTOP (CONTROL CAN) --> KVASER --> CAN GATEWAY
ALL MODULES POWERED THROUGH ARDUINO connected to LAPTOP
I don't have a physical control can bus. I am assuming my laptop will function as a control can bus.
No non-e power source.

Please let me know where I am wrong.

**Comment by vertexmachina** [comment]
Please see answer here: https://github.com/PolySync/oscc/issues/201
