### ISSUE TITLE
Controls disabling when steering hit far left and right positions

### ISSUE THREAD

**Issue by rg4444** [PolySync/oscc-joystick-commander#17]
While using joystick steering control from end to end - full left to right movements, when steering gear hit the end of movement - controls throw out error message and disable.

**Comment by nathanaschbacher** [comment]
Hi,

This behavior is called-out and partially documented in this section of the OSCC [README.md](https://github.com/PolySync/oscc#building-the-firmware).

If the steering override is too sensitive, then you have a few options for altering it's behavior to either disable it or make it less sensitive, but both changes come with important side-effects which should be considered and understood.

In the future we may spend more time and effort trying to continuously tune and optimize the steering override functionality, but with the limited data (just torque sensor amplitudes), limited compute capacity, and limited time budget it's difficult to discern between computer control and human intervention. 

In an ideal world we'd also have access to path planner outputs and vehicle dynamics to determine not only how much torque we're seeing at the sensor, but also much we should be seeing to maintain a target trajectory. For now though:

> Operator Overrides: While all OSCC modules have operator override detection enabled by default, attempting to grab the steering wheel while the system is active could result in serious injury. The preferred method of operator override for steering is to utilize the brake pedal or E-stop button. To disable operator override for the steering module, pass an additional flag to the CMake build step.

> If steering operator overrides remain enabled, the sensitivity can be adjusted by changing the value of the TORQUE_DIFFERENCE_OVERRIDE_THRESHOLD in the corresponding vehicle's header file.

> * Lowering this value will make the steering module more sensitive to operator override, but will result in false positives around high-torque areas, such as the mechanical limits of the steering rack or when quickly and rapidly changing direction.
> * Increasing this value will result in fewer false positives, but will make it more difficult to manually override the wheel.
