### ISSUE TITLE
Issue on KIA_SOUL_OBD_STEERING_ANGLE_SCALAR

### ISSUE THREAD

**Issue by JiaqiL** [PolySync/oscc-joystick-commander#22]
https://github.com/PolySync/oscc-joystick-commander/blob/d8806e978cb7eadda644b30bf235173a969407ee/src/commander.c#L530

Hi, I believe we should write: 

```
curr_angle = steering_data->steering_wheel_angle / KIA_SOUL_OBD_STEERING_ANGLE_SCALAR;
```

insteand of 

```
curr_angle = steering_data->steering_wheel_angle * KIA_SOUL_OBD_STEERING_ANGLE_SCALAR;
```

Please correct me if I'm wrong. 

Thanks !

**Comment by clearydude** [comment]
The raw steering wheel angle data that we get from the Kia's OBD CAN is in deci-degrees (1/10th of a degree), so to store the angle's representation in regular degrees we scale it down by a factor of 10 by multiplying it by 0.1. 
You could divide the raw value by 10 to get the same scaling, but multiplication is generally a faster operation than division.  
Hence 3653 deci-degrees retrieved from OBD message can be stored as 365.3 degrees.
