### ISSUE TITLE
Is this assignment correct? 

### ISSUE THREAD

**Issue by JiaqiL** [PolySync/oscc-joystick-commander#23]
https://github.com/PolySync/oscc-joystick-commander/blob/3b61d812ddfc0178bd19361156c48677a57c987e/src/joystick.c#L65

Please correct me if I am wrong. Thanks!

**Comment by shnewto** [comment]
Hi there @JiaqiL, thanks for raising this issue! I've pushed some changes to make this initialization more explicit, they're up in PR #24 . Good catch!
